### ISSUE TITLE
Review email templates 

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/awards-bot#6]
Hey @mbjones @aebudden @csjx @mpsaloha when you get a chance can you review the email templates that we're going to automatically email to NSF award recipients?  They're located in this folder https://github.com/NCEAS/awards-bot/tree/master/inst/emails.  Jesse, Kathryn and Marie already made edits, so hopefully there isn't much left to do.  

The most time efficient method might be to just comment any proposed changes in this issue, although using a fork / PR works too.  @mbjones could also grant push access to the repo - but that might be overkill for this issue.  

Thanks!

**Comment by mbjones** [comment]
@dmullen17 I discussed the award notification system and email templates with NSF today.  Overall they thought the system looked good and would be welcome.  They've asked for:

1) A single, integrated document that they could use to read and comment on all of the emails.  They found it hard to read the emails in github because of the lack of line wrapping and no way for them to easily provide comments.  Can you put this all in a Google doc that we can circulate for comments?

2) They reviewed the programs list, and said we should plan to email all of the programs in the list you generated, including:
```
1  AON IMPLEMENTATION   58
2  ARCTIC NATURAL SCIENCES  197
3  ARCTIC RESEARCH AND EDUCATION    2
4  ARCTIC RES & POLICY SUPPORT PR    3
5  ARCTIC RESRCH SUPPRT & LOGISTI    7
6  ARCTIC SOCIAL SCIENCES   96
7  ARCTIC SYSTEM SCIENCE PROGRAM  104
8  POLAR CYBERINFRASTRUCTURE   10
9  Polar Special Initiatives   14
```

They said apparently a few of those may have some awards that don't fall within the requirements, particularly ARCTIC RESRCH SUPPRT & LOGISTI, and maybe Polar Special Initiatives, but that it should be ok to email them anyways.

**Comment by dmullen17** [comment]
@mbjones sounds good.  Here's the link to the google doc.  If you give their email addresses I can send it to them; alternatively you can share the link https://docs.google.com/document/d/1-SjGpqJ4MEB2mvidCQGKVVMCchaoCrUiveN_-tgsWNo/edit?usp=sharing with them as well.
